// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: underwriting.proto

package loan_decision

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateLoanDecisionRequest message for creating a loan decision
type CreateLoanDecisionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LoanApplicationId uint64                 `protobuf:"varint,1,opt,name=loan_application_id,json=loanApplicationId,proto3" json:"loan_application_id,omitempty"` // Loan application ID
	AiDecision        string                 `protobuf:"bytes,2,opt,name=ai_decision,json=aiDecision,proto3" json:"ai_decision,omitempty"`                         // Decision from AI (approved/rejected)
	Reasoning         string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`                                             // Reasoning for the decision
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateLoanDecisionRequest) Reset() {
	*x = CreateLoanDecisionRequest{}
	mi := &file_underwriting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanDecisionRequest) ProtoMessage() {}

func (x *CreateLoanDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_underwriting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanDecisionRequest.ProtoReflect.Descriptor instead.
func (*CreateLoanDecisionRequest) Descriptor() ([]byte, []int) {
	return file_underwriting_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLoanDecisionRequest) GetLoanApplicationId() uint64 {
	if x != nil {
		return x.LoanApplicationId
	}
	return 0
}

func (x *CreateLoanDecisionRequest) GetAiDecision() string {
	if x != nil {
		return x.AiDecision
	}
	return ""
}

func (x *CreateLoanDecisionRequest) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

// CreateLoanDecisionResponse message for response after creating a loan decision
type CreateLoanDecisionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoanDecisionId uint64                 `protobuf:"varint,1,opt,name=loan_decision_id,json=loanDecisionId,proto3" json:"loan_decision_id,omitempty"` // Unique ID of the loan decision
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                          // Status message (e.g., "Created successfully")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLoanDecisionResponse) Reset() {
	*x = CreateLoanDecisionResponse{}
	mi := &file_underwriting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanDecisionResponse) ProtoMessage() {}

func (x *CreateLoanDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_underwriting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanDecisionResponse.ProtoReflect.Descriptor instead.
func (*CreateLoanDecisionResponse) Descriptor() ([]byte, []int) {
	return file_underwriting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLoanDecisionResponse) GetLoanDecisionId() uint64 {
	if x != nil {
		return x.LoanDecisionId
	}
	return 0
}

func (x *CreateLoanDecisionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetLoanDecisionRequest message to request an existing loan decision
type GetLoanDecisionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoanDecisionId uint64                 `protobuf:"varint,1,opt,name=loan_decision_id,json=loanDecisionId,proto3" json:"loan_decision_id,omitempty"` // ID of the loan decision to fetch
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLoanDecisionRequest) Reset() {
	*x = GetLoanDecisionRequest{}
	mi := &file_underwriting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanDecisionRequest) ProtoMessage() {}

func (x *GetLoanDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_underwriting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetLoanDecisionRequest) Descriptor() ([]byte, []int) {
	return file_underwriting_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoanDecisionRequest) GetLoanDecisionId() uint64 {
	if x != nil {
		return x.LoanDecisionId
	}
	return 0
}

// GetLoanDecisionResponse message containing the loan decision details
type GetLoanDecisionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LoanDecisionId    uint64                 `protobuf:"varint,1,opt,name=loan_decision_id,json=loanDecisionId,proto3" json:"loan_decision_id,omitempty"`          // Unique ID of the loan decision
	LoanApplicationId uint64                 `protobuf:"varint,2,opt,name=loan_application_id,json=loanApplicationId,proto3" json:"loan_application_id,omitempty"` // Associated loan application ID
	AiDecision        string                 `protobuf:"bytes,3,opt,name=ai_decision,json=aiDecision,proto3" json:"ai_decision,omitempty"`                         // Decision from AI (approved/rejected)
	Reasoning         string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`                                             // Reasoning for the decision
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                            // Timestamp of decision creation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLoanDecisionResponse) Reset() {
	*x = GetLoanDecisionResponse{}
	mi := &file_underwriting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanDecisionResponse) ProtoMessage() {}

func (x *GetLoanDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_underwriting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanDecisionResponse.ProtoReflect.Descriptor instead.
func (*GetLoanDecisionResponse) Descriptor() ([]byte, []int) {
	return file_underwriting_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoanDecisionResponse) GetLoanDecisionId() uint64 {
	if x != nil {
		return x.LoanDecisionId
	}
	return 0
}

func (x *GetLoanDecisionResponse) GetLoanApplicationId() uint64 {
	if x != nil {
		return x.LoanApplicationId
	}
	return 0
}

func (x *GetLoanDecisionResponse) GetAiDecision() string {
	if x != nil {
		return x.AiDecision
	}
	return ""
}

func (x *GetLoanDecisionResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *GetLoanDecisionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_underwriting_proto protoreflect.FileDescriptor

const file_underwriting_proto_rawDesc = "" +
	"\n" +
	"\x12underwriting.proto\x12\rloan_decision\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x19CreateLoanDecisionRequest\x12.\n" +
	"\x13loan_application_id\x18\x01 \x01(\x04R\x11loanApplicationId\x12\x1f\n" +
	"\vai_decision\x18\x02 \x01(\tR\n" +
	"aiDecision\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\"^\n" +
	"\x1aCreateLoanDecisionResponse\x12(\n" +
	"\x10loan_decision_id\x18\x01 \x01(\x04R\x0eloanDecisionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"B\n" +
	"\x16GetLoanDecisionRequest\x12(\n" +
	"\x10loan_decision_id\x18\x01 \x01(\x04R\x0eloanDecisionId\"\xed\x01\n" +
	"\x17GetLoanDecisionResponse\x12(\n" +
	"\x10loan_decision_id\x18\x01 \x01(\x04R\x0eloanDecisionId\x12.\n" +
	"\x13loan_application_id\x18\x02 \x01(\x04R\x11loanApplicationId\x12\x1f\n" +
	"\vai_decision\x18\x03 \x01(\tR\n" +
	"aiDecision\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xe2\x01\n" +
	"\x13LoanDecisionService\x12i\n" +
	"\x12CreateLoanDecision\x12(.loan_decision.CreateLoanDecisionRequest\x1a).loan_decision.CreateLoanDecisionResponse\x12`\n" +
	"\x0fGetLoanDecision\x12%.loan_decision.GetLoanDecisionRequest\x1a&.loan_decision.GetLoanDecisionResponseB%Z#Backend/created_proto/loan_decisionb\x06proto3"

var (
	file_underwriting_proto_rawDescOnce sync.Once
	file_underwriting_proto_rawDescData []byte
)

func file_underwriting_proto_rawDescGZIP() []byte {
	file_underwriting_proto_rawDescOnce.Do(func() {
		file_underwriting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_underwriting_proto_rawDesc), len(file_underwriting_proto_rawDesc)))
	})
	return file_underwriting_proto_rawDescData
}

var file_underwriting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_underwriting_proto_goTypes = []any{
	(*CreateLoanDecisionRequest)(nil),  // 0: loan_decision.CreateLoanDecisionRequest
	(*CreateLoanDecisionResponse)(nil), // 1: loan_decision.CreateLoanDecisionResponse
	(*GetLoanDecisionRequest)(nil),     // 2: loan_decision.GetLoanDecisionRequest
	(*GetLoanDecisionResponse)(nil),    // 3: loan_decision.GetLoanDecisionResponse
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_underwriting_proto_depIdxs = []int32{
	4, // 0: loan_decision.GetLoanDecisionResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: loan_decision.LoanDecisionService.CreateLoanDecision:input_type -> loan_decision.CreateLoanDecisionRequest
	2, // 2: loan_decision.LoanDecisionService.GetLoanDecision:input_type -> loan_decision.GetLoanDecisionRequest
	1, // 3: loan_decision.LoanDecisionService.CreateLoanDecision:output_type -> loan_decision.CreateLoanDecisionResponse
	3, // 4: loan_decision.LoanDecisionService.GetLoanDecision:output_type -> loan_decision.GetLoanDecisionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_underwriting_proto_init() }
func file_underwriting_proto_init() {
	if File_underwriting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_underwriting_proto_rawDesc), len(file_underwriting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_underwriting_proto_goTypes,
		DependencyIndexes: file_underwriting_proto_depIdxs,
		MessageInfos:      file_underwriting_proto_msgTypes,
	}.Build()
	File_underwriting_proto = out.File
	file_underwriting_proto_goTypes = nil
	file_underwriting_proto_depIdxs = nil
}
