// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: loan.proto

package loan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoanRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                              // User submitting the loan application
	LoanAmount       float64                `protobuf:"fixed64,2,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`                 // Amount requested for the loan
	LoanTerm         int32                  `protobuf:"varint,3,opt,name=loan_term,json=loanTerm,proto3" json:"loan_term,omitempty"`                        // Loan term in months or years
	LoanPurpose      string                 `protobuf:"bytes,4,opt,name=loan_purpose,json=loanPurpose,proto3" json:"loan_purpose,omitempty"`                // Purpose of the loan
	EmploymentStatus string                 `protobuf:"bytes,5,opt,name=employment_status,json=employmentStatus,proto3" json:"employment_status,omitempty"` // Employment status of the user
	AnnualIncome     float64                `protobuf:"fixed64,6,opt,name=annual_income,json=annualIncome,proto3" json:"annual_income,omitempty"`           // User's annual income
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoanRequest) Reset() {
	*x = LoanRequest{}
	mi := &file_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanRequest) ProtoMessage() {}

func (x *LoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanRequest.ProtoReflect.Descriptor instead.
func (*LoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{0}
}

func (x *LoanRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoanRequest) GetLoanAmount() float64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *LoanRequest) GetLoanTerm() int32 {
	if x != nil {
		return x.LoanTerm
	}
	return 0
}

func (x *LoanRequest) GetLoanPurpose() string {
	if x != nil {
		return x.LoanPurpose
	}
	return ""
}

func (x *LoanRequest) GetEmploymentStatus() string {
	if x != nil {
		return x.EmploymentStatus
	}
	return ""
}

func (x *LoanRequest) GetAnnualIncome() float64 {
	if x != nil {
		return x.AnnualIncome
	}
	return 0
}

type LoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        uint64                 `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"` // Unique loan ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                // Loan status (e.g., "Pending", "Approved", "Rejected")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanResponse) Reset() {
	*x = LoanResponse{}
	mi := &file_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanResponse) ProtoMessage() {}

func (x *LoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanResponse.ProtoReflect.Descriptor instead.
func (*LoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{1}
}

func (x *LoanResponse) GetLoanId() uint64 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

func (x *LoanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoanStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        uint64                 `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"` // Loan ID to get status of
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanStatusRequest) Reset() {
	*x = LoanStatusRequest{}
	mi := &file_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanStatusRequest) ProtoMessage() {}

func (x *LoanStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanStatusRequest.ProtoReflect.Descriptor instead.
func (*LoanStatusRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{2}
}

func (x *LoanStatusRequest) GetLoanId() uint64 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

type LoanStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        uint64                 `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"` // Loan ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                // Loan application status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanStatusResponse) Reset() {
	*x = LoanStatusResponse{}
	mi := &file_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanStatusResponse) ProtoMessage() {}

func (x *LoanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanStatusResponse.ProtoReflect.Descriptor instead.
func (*LoanStatusResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{3}
}

func (x *LoanStatusResponse) GetLoanId() uint64 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

func (x *LoanStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoanApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        uint64                 `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"` // Request details of a specific loan application
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanApplicationRequest) Reset() {
	*x = LoanApplicationRequest{}
	mi := &file_loan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanApplicationRequest) ProtoMessage() {}

func (x *LoanApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanApplicationRequest.ProtoReflect.Descriptor instead.
func (*LoanApplicationRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{4}
}

func (x *LoanApplicationRequest) GetLoanId() uint64 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

type LoanApplicationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LoanId              uint64                 `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`                                          // Unique loan application ID
	UserId              uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                          // User ID of the applicant
	LoanAmount          float64                `protobuf:"fixed64,3,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`                             // Requested loan amount
	LoanPurpose         string                 `protobuf:"bytes,4,opt,name=loan_purpose,json=loanPurpose,proto3" json:"loan_purpose,omitempty"`                            // Purpose of the loan
	EmploymentStatus    string                 `protobuf:"bytes,5,opt,name=employment_status,json=employmentStatus,proto3" json:"employment_status,omitempty"`             // Employment status of the user
	AnnualIncome        float64                `protobuf:"fixed64,6,opt,name=annual_income,json=annualIncome,proto3" json:"annual_income,omitempty"`                       // User's annual income
	ApplicationStatus   string                 `protobuf:"bytes,7,opt,name=application_status,json=applicationStatus,proto3" json:"application_status,omitempty"`          // Application status (e.g., "Pending", "Approved", "Rejected")
	CreditReportFetched bool                   `protobuf:"varint,8,opt,name=credit_report_fetched,json=creditReportFetched,proto3" json:"credit_report_fetched,omitempty"` // Whether the credit report has been fetched
	ExperianRequestId   string                 `protobuf:"bytes,9,opt,name=experian_request_id,json=experianRequestId,proto3" json:"experian_request_id,omitempty"`        // Experian API request ID
	CreditScore         int32                  `protobuf:"varint,10,opt,name=credit_score,json=creditScore,proto3" json:"credit_score,omitempty"`                          // Credit score fetched from Experian
	CreatedAt           string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                 // Date when the loan application was created (consider using timestamp)
	UpdatedAt           string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                 // Date when the loan application was last updated (consider using timestamp)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoanApplicationResponse) Reset() {
	*x = LoanApplicationResponse{}
	mi := &file_loan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanApplicationResponse) ProtoMessage() {}

func (x *LoanApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanApplicationResponse.ProtoReflect.Descriptor instead.
func (*LoanApplicationResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{5}
}

func (x *LoanApplicationResponse) GetLoanId() uint64 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

func (x *LoanApplicationResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoanApplicationResponse) GetLoanAmount() float64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *LoanApplicationResponse) GetLoanPurpose() string {
	if x != nil {
		return x.LoanPurpose
	}
	return ""
}

func (x *LoanApplicationResponse) GetEmploymentStatus() string {
	if x != nil {
		return x.EmploymentStatus
	}
	return ""
}

func (x *LoanApplicationResponse) GetAnnualIncome() float64 {
	if x != nil {
		return x.AnnualIncome
	}
	return 0
}

func (x *LoanApplicationResponse) GetApplicationStatus() string {
	if x != nil {
		return x.ApplicationStatus
	}
	return ""
}

func (x *LoanApplicationResponse) GetCreditReportFetched() bool {
	if x != nil {
		return x.CreditReportFetched
	}
	return false
}

func (x *LoanApplicationResponse) GetExperianRequestId() string {
	if x != nil {
		return x.ExperianRequestId
	}
	return ""
}

func (x *LoanApplicationResponse) GetCreditScore() int32 {
	if x != nil {
		return x.CreditScore
	}
	return 0
}

func (x *LoanApplicationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LoanApplicationResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_loan_proto protoreflect.FileDescriptor

const file_loan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"loan.proto\x12\x04loan\"\xd9\x01\n" +
	"\vLoanRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vloan_amount\x18\x02 \x01(\x01R\n" +
	"loanAmount\x12\x1b\n" +
	"\tloan_term\x18\x03 \x01(\x05R\bloanTerm\x12!\n" +
	"\floan_purpose\x18\x04 \x01(\tR\vloanPurpose\x12+\n" +
	"\x11employment_status\x18\x05 \x01(\tR\x10employmentStatus\x12#\n" +
	"\rannual_income\x18\x06 \x01(\x01R\fannualIncome\"?\n" +
	"\fLoanResponse\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\x04R\x06loanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\",\n" +
	"\x11LoanStatusRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\x04R\x06loanId\"E\n" +
	"\x12LoanStatusResponse\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\x04R\x06loanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"1\n" +
	"\x16LoanApplicationRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\x04R\x06loanId\"\xd5\x03\n" +
	"\x17LoanApplicationResponse\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\x04R\x06loanId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vloan_amount\x18\x03 \x01(\x01R\n" +
	"loanAmount\x12!\n" +
	"\floan_purpose\x18\x04 \x01(\tR\vloanPurpose\x12+\n" +
	"\x11employment_status\x18\x05 \x01(\tR\x10employmentStatus\x12#\n" +
	"\rannual_income\x18\x06 \x01(\x01R\fannualIncome\x12-\n" +
	"\x12application_status\x18\a \x01(\tR\x11applicationStatus\x122\n" +
	"\x15credit_report_fetched\x18\b \x01(\bR\x13creditReportFetched\x12.\n" +
	"\x13experian_request_id\x18\t \x01(\tR\x11experianRequestId\x12!\n" +
	"\fcredit_score\x18\n" +
	" \x01(\x05R\vcreditScore\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt2\xe2\x01\n" +
	"\vLoanService\x125\n" +
	"\fApplyForLoan\x12\x11.loan.LoanRequest\x1a\x12.loan.LoanResponse\x12B\n" +
	"\rGetLoanStatus\x12\x17.loan.LoanStatusRequest\x1a\x18.loan.LoanStatusResponse\x12X\n" +
	"\x19GetLoanApplicationDetails\x12\x1c.loan.LoanApplicationRequest\x1a\x1d.loan.LoanApplicationResponseB\x1cZ\x1aBackend/created_proto/loanb\x06proto3"

var (
	file_loan_proto_rawDescOnce sync.Once
	file_loan_proto_rawDescData []byte
)

func file_loan_proto_rawDescGZIP() []byte {
	file_loan_proto_rawDescOnce.Do(func() {
		file_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_proto_rawDesc), len(file_loan_proto_rawDesc)))
	})
	return file_loan_proto_rawDescData
}

var file_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_loan_proto_goTypes = []any{
	(*LoanRequest)(nil),             // 0: loan.LoanRequest
	(*LoanResponse)(nil),            // 1: loan.LoanResponse
	(*LoanStatusRequest)(nil),       // 2: loan.LoanStatusRequest
	(*LoanStatusResponse)(nil),      // 3: loan.LoanStatusResponse
	(*LoanApplicationRequest)(nil),  // 4: loan.LoanApplicationRequest
	(*LoanApplicationResponse)(nil), // 5: loan.LoanApplicationResponse
}
var file_loan_proto_depIdxs = []int32{
	0, // 0: loan.LoanService.ApplyForLoan:input_type -> loan.LoanRequest
	2, // 1: loan.LoanService.GetLoanStatus:input_type -> loan.LoanStatusRequest
	4, // 2: loan.LoanService.GetLoanApplicationDetails:input_type -> loan.LoanApplicationRequest
	1, // 3: loan.LoanService.ApplyForLoan:output_type -> loan.LoanResponse
	3, // 4: loan.LoanService.GetLoanStatus:output_type -> loan.LoanStatusResponse
	5, // 5: loan.LoanService.GetLoanApplicationDetails:output_type -> loan.LoanApplicationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loan_proto_init() }
func file_loan_proto_init() {
	if File_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_proto_rawDesc), len(file_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_proto_goTypes,
		DependencyIndexes: file_loan_proto_depIdxs,
		MessageInfos:      file_loan_proto_msgTypes,
	}.Build()
	File_loan_proto = out.File
	file_loan_proto_goTypes = nil
	file_loan_proto_depIdxs = nil
}
