// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package loan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanServiceClient interface {
	ApplyForLoan(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*LoanResponse, error)
	GetLoanStatus(ctx context.Context, in *LoanStatusRequest, opts ...grpc.CallOption) (*LoanStatusResponse, error)
	GetLoanApplicationDetails(ctx context.Context, in *LoanApplicationRequest, opts ...grpc.CallOption) (*LoanApplicationResponse, error)
	GetAllLoanApplications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoanApplicationList, error)
	UpdateApplicationStatus(ctx context.Context, in *UpdateApplicationStatusRequest, opts ...grpc.CallOption) (*UpdateApplicationStatusResponse, error)
	GetLoanStatusCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoanStatsResponse, error)
}

type loanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanServiceClient(cc grpc.ClientConnInterface) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) ApplyForLoan(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*LoanResponse, error) {
	out := new(LoanResponse)
	err := c.cc.Invoke(ctx, "/loan.LoanService/ApplyForLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanStatus(ctx context.Context, in *LoanStatusRequest, opts ...grpc.CallOption) (*LoanStatusResponse, error) {
	out := new(LoanStatusResponse)
	err := c.cc.Invoke(ctx, "/loan.LoanService/GetLoanStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanApplicationDetails(ctx context.Context, in *LoanApplicationRequest, opts ...grpc.CallOption) (*LoanApplicationResponse, error) {
	out := new(LoanApplicationResponse)
	err := c.cc.Invoke(ctx, "/loan.LoanService/GetLoanApplicationDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetAllLoanApplications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoanApplicationList, error) {
	out := new(LoanApplicationList)
	err := c.cc.Invoke(ctx, "/loan.LoanService/GetAllLoanApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) UpdateApplicationStatus(ctx context.Context, in *UpdateApplicationStatusRequest, opts ...grpc.CallOption) (*UpdateApplicationStatusResponse, error) {
	out := new(UpdateApplicationStatusResponse)
	err := c.cc.Invoke(ctx, "/loan.LoanService/UpdateApplicationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanStatusCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoanStatsResponse, error) {
	out := new(LoanStatsResponse)
	err := c.cc.Invoke(ctx, "/loan.LoanService/GetLoanStatusCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
// All implementations must embed UnimplementedLoanServiceServer
// for forward compatibility
type LoanServiceServer interface {
	ApplyForLoan(context.Context, *LoanRequest) (*LoanResponse, error)
	GetLoanStatus(context.Context, *LoanStatusRequest) (*LoanStatusResponse, error)
	GetLoanApplicationDetails(context.Context, *LoanApplicationRequest) (*LoanApplicationResponse, error)
	GetAllLoanApplications(context.Context, *Empty) (*LoanApplicationList, error)
	UpdateApplicationStatus(context.Context, *UpdateApplicationStatusRequest) (*UpdateApplicationStatusResponse, error)
	GetLoanStatusCount(context.Context, *Empty) (*LoanStatsResponse, error)
	mustEmbedUnimplementedLoanServiceServer()
}

// UnimplementedLoanServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoanServiceServer struct {
}

func (UnimplementedLoanServiceServer) ApplyForLoan(context.Context, *LoanRequest) (*LoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyForLoan not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanStatus(context.Context, *LoanStatusRequest) (*LoanStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoanStatus not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanApplicationDetails(context.Context, *LoanApplicationRequest) (*LoanApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoanApplicationDetails not implemented")
}
func (UnimplementedLoanServiceServer) GetAllLoanApplications(context.Context, *Empty) (*LoanApplicationList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLoanApplications not implemented")
}
func (UnimplementedLoanServiceServer) UpdateApplicationStatus(context.Context, *UpdateApplicationStatusRequest) (*UpdateApplicationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApplicationStatus not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanStatusCount(context.Context, *Empty) (*LoanStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoanStatusCount not implemented")
}
func (UnimplementedLoanServiceServer) mustEmbedUnimplementedLoanServiceServer() {}

// UnsafeLoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServiceServer will
// result in compilation errors.
type UnsafeLoanServiceServer interface {
	mustEmbedUnimplementedLoanServiceServer()
}

func RegisterLoanServiceServer(s grpc.ServiceRegistrar, srv LoanServiceServer) {
	s.RegisterService(&LoanService_ServiceDesc, srv)
}

func _LoanService_ApplyForLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ApplyForLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loan.LoanService/ApplyForLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ApplyForLoan(ctx, req.(*LoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loan.LoanService/GetLoanStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanStatus(ctx, req.(*LoanStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanApplicationDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanApplicationDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loan.LoanService/GetLoanApplicationDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanApplicationDetails(ctx, req.(*LoanApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetAllLoanApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetAllLoanApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loan.LoanService/GetAllLoanApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetAllLoanApplications(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_UpdateApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).UpdateApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loan.LoanService/UpdateApplicationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).UpdateApplicationStatus(ctx, req.(*UpdateApplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanStatusCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanStatusCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loan.LoanService/GetLoanStatusCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanStatusCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanService_ServiceDesc is the grpc.ServiceDesc for LoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loan.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyForLoan",
			Handler:    _LoanService_ApplyForLoan_Handler,
		},
		{
			MethodName: "GetLoanStatus",
			Handler:    _LoanService_GetLoanStatus_Handler,
		},
		{
			MethodName: "GetLoanApplicationDetails",
			Handler:    _LoanService_GetLoanApplicationDetails_Handler,
		},
		{
			MethodName: "GetAllLoanApplications",
			Handler:    _LoanService_GetAllLoanApplications_Handler,
		},
		{
			MethodName: "UpdateApplicationStatus",
			Handler:    _LoanService_UpdateApplicationStatus_Handler,
		},
		{
			MethodName: "GetLoanStatusCount",
			Handler:    _LoanService_GetLoanStatusCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loan.proto",
}
