// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: loan_Payment.proto

package loan_payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateLoanPaymentRequest message for making a loan payment
type CreateLoanPaymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LoanApplicationId uint64                 `protobuf:"varint,1,opt,name=loan_application_id,json=loanApplicationId,proto3" json:"loan_application_id,omitempty"`
	AmountPaid        float64                `protobuf:"fixed64,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PaymentDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	DueDate           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"` // ✅ New field
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateLoanPaymentRequest) Reset() {
	*x = CreateLoanPaymentRequest{}
	mi := &file_loan_Payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanPaymentRequest) ProtoMessage() {}

func (x *CreateLoanPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_Payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanPaymentRequest.ProtoReflect.Descriptor instead.
func (*CreateLoanPaymentRequest) Descriptor() ([]byte, []int) {
	return file_loan_Payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLoanPaymentRequest) GetLoanApplicationId() uint64 {
	if x != nil {
		return x.LoanApplicationId
	}
	return 0
}

func (x *CreateLoanPaymentRequest) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *CreateLoanPaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateLoanPaymentRequest) GetPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentDate
	}
	return nil
}

func (x *CreateLoanPaymentRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

// CreateLoanPaymentResponse message for response after creating a loan payment
type CreateLoanPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanPaymentId uint64                 `protobuf:"varint,1,opt,name=loan_payment_id,json=loanPaymentId,proto3" json:"loan_payment_id,omitempty"` // Unique ID of the loan payment
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                       // Status message (e.g., "Payment successful")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanPaymentResponse) Reset() {
	*x = CreateLoanPaymentResponse{}
	mi := &file_loan_Payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanPaymentResponse) ProtoMessage() {}

func (x *CreateLoanPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_Payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanPaymentResponse.ProtoReflect.Descriptor instead.
func (*CreateLoanPaymentResponse) Descriptor() ([]byte, []int) {
	return file_loan_Payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLoanPaymentResponse) GetLoanPaymentId() uint64 {
	if x != nil {
		return x.LoanPaymentId
	}
	return 0
}

func (x *CreateLoanPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetLoanPaymentRequest message to request an existing loan payment
type GetLoanPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanPaymentId uint64                 `protobuf:"varint,1,opt,name=loan_payment_id,json=loanPaymentId,proto3" json:"loan_payment_id,omitempty"` // ID of the loan payment to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanPaymentRequest) Reset() {
	*x = GetLoanPaymentRequest{}
	mi := &file_loan_Payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanPaymentRequest) ProtoMessage() {}

func (x *GetLoanPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_Payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetLoanPaymentRequest) Descriptor() ([]byte, []int) {
	return file_loan_Payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoanPaymentRequest) GetLoanPaymentId() uint64 {
	if x != nil {
		return x.LoanPaymentId
	}
	return 0
}

// GetLoanPaymentResponse message containing the loan payment details
type GetLoanPaymentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LoanPaymentId     uint64                 `protobuf:"varint,1,opt,name=loan_payment_id,json=loanPaymentId,proto3" json:"loan_payment_id,omitempty"`
	LoanApplicationId uint64                 `protobuf:"varint,2,opt,name=loan_application_id,json=loanApplicationId,proto3" json:"loan_application_id,omitempty"`
	AmountPaid        float64                `protobuf:"fixed64,3,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PaymentDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	DueDate           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"` // ✅ New field
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLoanPaymentResponse) Reset() {
	*x = GetLoanPaymentResponse{}
	mi := &file_loan_Payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanPaymentResponse) ProtoMessage() {}

func (x *GetLoanPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_Payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetLoanPaymentResponse) Descriptor() ([]byte, []int) {
	return file_loan_Payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoanPaymentResponse) GetLoanPaymentId() uint64 {
	if x != nil {
		return x.LoanPaymentId
	}
	return 0
}

func (x *GetLoanPaymentResponse) GetLoanApplicationId() uint64 {
	if x != nil {
		return x.LoanApplicationId
	}
	return 0
}

func (x *GetLoanPaymentResponse) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *GetLoanPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetLoanPaymentResponse) GetPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentDate
	}
	return nil
}

func (x *GetLoanPaymentResponse) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

var File_loan_Payment_proto protoreflect.FileDescriptor

const file_loan_Payment_proto_rawDesc = "" +
	"\n" +
	"\x12loan_Payment.proto\x12\floan_payment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\x18CreateLoanPaymentRequest\x12.\n" +
	"\x13loan_application_id\x18\x01 \x01(\x04R\x11loanApplicationId\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\x01R\n" +
	"amountPaid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12=\n" +
	"\fpayment_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vpaymentDate\x125\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"[\n" +
	"\x19CreateLoanPaymentResponse\x12&\n" +
	"\x0floan_payment_id\x18\x01 \x01(\x04R\rloanPaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"?\n" +
	"\x15GetLoanPaymentRequest\x12&\n" +
	"\x0floan_payment_id\x18\x01 \x01(\x04R\rloanPaymentId\"\x9f\x02\n" +
	"\x16GetLoanPaymentResponse\x12&\n" +
	"\x0floan_payment_id\x18\x01 \x01(\x04R\rloanPaymentId\x12.\n" +
	"\x13loan_application_id\x18\x02 \x01(\x04R\x11loanApplicationId\x12\x1f\n" +
	"\vamount_paid\x18\x03 \x01(\x01R\n" +
	"amountPaid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12=\n" +
	"\fpayment_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vpaymentDate\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate2\xd7\x01\n" +
	"\x12LoanPaymentService\x12d\n" +
	"\x11CreateLoanPayment\x12&.loan_payment.CreateLoanPaymentRequest\x1a'.loan_payment.CreateLoanPaymentResponse\x12[\n" +
	"\x0eGetLoanPayment\x12#.loan_payment.GetLoanPaymentRequest\x1a$.loan_payment.GetLoanPaymentResponseB$Z\"Backend/created_proto/loan_paymentb\x06proto3"

var (
	file_loan_Payment_proto_rawDescOnce sync.Once
	file_loan_Payment_proto_rawDescData []byte
)

func file_loan_Payment_proto_rawDescGZIP() []byte {
	file_loan_Payment_proto_rawDescOnce.Do(func() {
		file_loan_Payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_Payment_proto_rawDesc), len(file_loan_Payment_proto_rawDesc)))
	})
	return file_loan_Payment_proto_rawDescData
}

var file_loan_Payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_loan_Payment_proto_goTypes = []any{
	(*CreateLoanPaymentRequest)(nil),  // 0: loan_payment.CreateLoanPaymentRequest
	(*CreateLoanPaymentResponse)(nil), // 1: loan_payment.CreateLoanPaymentResponse
	(*GetLoanPaymentRequest)(nil),     // 2: loan_payment.GetLoanPaymentRequest
	(*GetLoanPaymentResponse)(nil),    // 3: loan_payment.GetLoanPaymentResponse
	(*timestamppb.Timestamp)(nil),     // 4: google.protobuf.Timestamp
}
var file_loan_Payment_proto_depIdxs = []int32{
	4, // 0: loan_payment.CreateLoanPaymentRequest.payment_date:type_name -> google.protobuf.Timestamp
	4, // 1: loan_payment.CreateLoanPaymentRequest.due_date:type_name -> google.protobuf.Timestamp
	4, // 2: loan_payment.GetLoanPaymentResponse.payment_date:type_name -> google.protobuf.Timestamp
	4, // 3: loan_payment.GetLoanPaymentResponse.due_date:type_name -> google.protobuf.Timestamp
	0, // 4: loan_payment.LoanPaymentService.CreateLoanPayment:input_type -> loan_payment.CreateLoanPaymentRequest
	2, // 5: loan_payment.LoanPaymentService.GetLoanPayment:input_type -> loan_payment.GetLoanPaymentRequest
	1, // 6: loan_payment.LoanPaymentService.CreateLoanPayment:output_type -> loan_payment.CreateLoanPaymentResponse
	3, // 7: loan_payment.LoanPaymentService.GetLoanPayment:output_type -> loan_payment.GetLoanPaymentResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_loan_Payment_proto_init() }
func file_loan_Payment_proto_init() {
	if File_loan_Payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_Payment_proto_rawDesc), len(file_loan_Payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_Payment_proto_goTypes,
		DependencyIndexes: file_loan_Payment_proto_depIdxs,
		MessageInfos:      file_loan_Payment_proto_msgTypes,
	}.Build()
	File_loan_Payment_proto = out.File
	file_loan_Payment_proto_goTypes = nil
	file_loan_Payment_proto_depIdxs = nil
}
