version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME_EXTERNAL: OUTSIDE
      KAFKA_LISTENER_PORT_EXTERNAL: 9092
      KAFKA_LISTENER_INTERPROCESS_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_INTERNAL: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENER_PORT_INTERNAL: 9093
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
